einride/iam-go

cmd/iamctl/internal/examplecmd/exampleservercmd/server.go, iamauthz/doc.go, iamauthz/middleware.go, iamauthz/middleware_test.go, iamexample/authorization.go, iamexample/server_test.go
As a belt-and-suspenders approach to ensure that authorization has been
performed on all RPC methods in a service, this middleware requires
authorization implementations to call `iamauthz.Authorize(ctx)` to mark
the request as authorized.
Requests that return without being marked as authorized are stopped by
the middleware, instead returning INTERNAL (signaling that the
implementer of the RPC method has not correctly implemented
authorization).
=> iamauthz middleware

.github/dependabot.yml
This is a separate module to encapsulate the CLI-specific dependencies.
=> chore: add iamctl to dependabot.yml

iampermission/match_test.go, iampermission/validate.go, iampermission/validate_test.go
In accordance with:
https://cloud.google.com/iam/docs/understanding-roles#predefined_roles
=> fix: allow camelCase in permission service names

iamreflect/iamdescriptor.go
The Get-functions handle when the receiver is nil.
=> fix: correctly handle missing long-running operations authorization

iamregistry/roles.go, iamregistry/roles_test.go, iamspanner/server.go, iamspanner/server_bindings_read.go, iamspanner/server_permissions.go, iamspanner/server_policies.go, iamspanner/server_policies_get.go, iamspanner/server_policies_set.go
All methods that read bindings are now called Read(...) and all take a
callback on the exact same format (a callback for a single binding).
No more methods on the IAMServer are called Query(...).
=> feat(iamspanner): simplify API

cmd/iamctl/internal/examplecmd/exampleservercmd/server.go, go.mod, iamexample/members.go, iammember/chain_test.go, iammember/resolver.go
Can be used for determining if any of the tokens have changed, for
example to invalidate cached authorization information.
=> feat: add checksum to iammember.ResolveResult

cmd/iamctl/internal/examplecmd/exampleservercmd/server.go, iamexample/server_test.go, iamregistry/roles.go, iamregistry/roles_test.go, iamspanner/server.go, iamspanner/server_test.go
Prefer using the standard type whenever possible, and let the rest be
internal implementation details.
BREAKING CHANGE: Creating a new Spanner IAM server now requires
[]*admin.Role instead of *iamregistry.Roles.
=> feat: prefer []*admin.Role over *iamv1.Roles in public API

cmd/protoc-gen-go-iam/internal/geniam/gen.go, cmd/protoc-gen-go-iam/main.go, iamauthz/beforelongrunning.go, iamcel/test.go, iamcel/testall.go, iamcel/testany.go, iampermission/longrunningoperationpermission.go, iampermission/resourcepermission.go, iampermission/resourcepermission_test.go, iamreflect/iamdescriptor.go, iamreflect/validate.go, iamreflect/validate_test.go, iamrole/validate.go, iamrole/validate_test.go
Compilation is now halted with an error message when the annotations
fail validation, parsing or type-checking.
=> feat(proto-gen-go-iam): add validation and type-checking

cmd/protoc-gen-go-iam/internal/geniam/authorization.go, proto/gen/einride/iam/example/v1/freight_service_iam.pb.go
When a service has only `none` or `custom` authorization, the descriptor
will be unused in the generated authorization constructor.
Adding an underscore assignment prevents this from halting compilation.
=> fix: mitigate unused variable

iamauthz/after.go, iamauthz/before.go, iamauthz/errors.go, iamcel/test.go, iamcel/testall.go, iamcel/testany.go, iamexample/server_iam_test.go, iamexample/server_test.go
Prevents errors from CEL functions causing code Unknown at the API
level, which would trigger alerts.
=> feat: forward error codes from CEL functions

iamauthz/errors.go, iamcel/test.go, iamcel/testall.go, iamcel/testany.go
When permission testing involves remote procedure calls, status codes
need to be forwarded through the CEL errors.
=> fix: forward status codes from permission test functions

cmd/iamctl/internal/connection/args.go
ESPv2 requires the prefix to be capitalized.
=> fix: use Bearer, not bearer for tokens

iamgoogle/idtoken.go, iamgoogle/idtoken_test.go
Some ID tokens are issued without https:// prefix, and this patch
enables the library to recognize them correctly.
=> fix(iamgoogle): recognize ID tokens without https:// in issuer

iamcel/testall.go
Important edge case for search methods that don't return any results.
=> fix(iamcel): test_all returns true for empty resources

iamtest/permissiontester.go, iamtest/permissiontester_test.go
Same behavior as the TestPermissions Spanner implementation (reference
implementation).
=> fix(iamtest): always return all input resources in output

iamcel/testall.go, iamcel/testany.go
No need to check length of result when looping through and testing the
original resources is sufficient.
=> fix: simplify CEL permission test functions

cmd/protoc-gen-go-iam/internal/geniam/authorization.go
No matter the authorization implementation (none, before, custom).
=> fix(protoc-gen-go-iam): always generate long-running methods

.sage/proto.go, iamauthz/after.go, iamauthz/before.go
Buf can sometimes time out if you try and do too many things
concurrently that require module downloading.
=> fix: improve sequencing of proto targets

iamgoogle/payload.go, iamgoogle/payload_test.go
Currently this function only recognizes user-managed service accounts. This would not capture default service accounts or google managed service accounts. 
https://cloud.google.com/iam/docs/service-accounts#types
=> feat: recognize multiple types of google service accounts

iamspanner/server_policies_set.go, iamspanner/server_test.go
The added SetIamPolicyWithFunctionsInTransaction does the same thing as SetIamPolicy used to do, but allows for passing in optional functions to be called within the database transaction.
This allows for additional writes to be made within the same transaction, making it possible e.g. to write to an outbox table within the same transaction.
=> feat(iamspanner): provide functions in SetIamPolicy transaction

iamauthz/errors.go
Otherwise the error code will be lost and converted to Unknown.
=> fix(iamauthz): forward Unavailable error code

README.md, iamauthz/after.go, iamauthz/before.go, iamcel/after.go, iamcel/before.go, iamcel/member.go, iamcel/member_test.go, iamcel/test.go, iamcel/testall.go, iamcel/testany.go
Introduce a member function on the caller object, to extract the first member value of a member kind, or fail if there are none.
=> feat(iamcel): add member function on caller object 

README.md, go.mod, go.sum, iamauthz/after.go, iamauthz/before.go, iamcel/after.go, iamcel/before.go, iamcel/join.go, iamcel/join_test.go
Join function combines two resource names, using [resourcename.Join] from aip-go.
[resourcename.Join]: https://pkg.go.dev/go.einride.tech/aip/resourcename#Join
=> feat(iamcel): add join function

.sage/go.mod, .sage/go.sum, proto/einride/iam/example/v1/freight_service.proto, proto/gen/einride/iam/example/v1/freight_service_grpc.pb.go
Replaces #672
Bumps [go.einride.tech/sage](https://github.com/einride/sage) from 0.282.0 to 0.291.0.
- [Release notes](https://github.com/einride/sage/releases)
- [Commits](https://github.com/einride/sage/compare/v0.282.0...v0.291.0)
---
updated-dependencies:
- dependency-name: go.einride.tech/sage
dependency-type: direct:production
update-type: version-update:semver-minor
...
Signed-off-by: dependabot[bot] <support@github.com>
=> chore(deps): bump go.einride.tech/sage from 0.282.0 to 0.291.0 in /.sage

.github/dependabot.yml
- We are getting a lot of these dependabot PRs, and often!
- Update schedule to monthly interval.
- This PR was generated with [multipr](https://github.com/fredrikaverpil/multipr)
=> ci(dependabot): update interval to monthly
